version: "3.1"
services:
  #php Service
  app:
    container_name: container_app
    build: php
    tty: true
    volumes:
      - ./php/bs23-app:/var/www/html
      - /var/www/html/vendor/
    # command: php -S laravel:80 -t public
    networks:
      - bs23-network
    depends_on:
      - db

  #Nginx Service
  webserver:
    container_name: container_webserver
    build: nginx
    #restart: unless-stopped
    tty: true
    ports:
      - "8700:80"
    volumes:
      - ./php/bs23-app:/var/www/html
      - /var/www/html/vendor/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - bs23-network
    depends_on:
      - db
      - app

  #MySQL Service
  db:
    container_name: container_db
    command: --default-authentication-plugin=mysql_native_password
    build: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3430:3306"
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
    networks:
      - bs23-network

networks:
  bs23-network:
    external:
      name: bs23-network
